[build]
  command = "node scripts/generate-config.js"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "config.js"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
